// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fwydmmvpmmoblbyyfkkh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ3eWRtbXZwbW1vYmxieXlma2toIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyMjUwNzIsImV4cCI6MjA1NTgwMTA3Mn0.8G2lYQDGjBf24FVSHcSLFqM9_9x4iIh4glli5cPqklc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);